version: "3.9"

services:
  docker:
    image: docker:dind
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    privileged: true
    volumes:
      - certs:/certs/

  runner:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GHA_RUNNER_TOKEN=$GHA_RUNNER_TOKEN
        - GHA_RUNNER_JWT_TOKEN=$GHA_RUNNER_JWT_TOKEN
        - GHA_RUNNER_DOWNLAOD_URL=$GHA_RUNNER_DOWNLAOD_URL
        - GH_REPO_URL=$GH_REPO_URL
    env_file:
      - .env
    environment:
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_TLS_VERIFY=1
    volumes:
      - certs:/certs:ro
    depends_on:
      - docker

volumes: 
  certs:
